### ISSUE TITLE
Исправления в вьюхах и сериализаторах

### ISSUE THREAD

**Issue by kelizarov** [kolodnikovm/newsblog#1]
Попробуй использовать `viewsets` для своих вьюх и посмотреть где их можно лучше применить, и еще посмотри как `NestedSerializers` работают для вложенных полей.

**Comment by kolodnikovm** [comment]
`viewsets` при текущей реализации удобно использовать при работе с юзерами только:

> we only need to specify the queryset once, and it'll be used across multiple views

В остальных случаях `queryset` каждой view свой.

Про `NestetSerializers` имелся в виду параметр `depth` метакласса? Я пробовал его, но, наверное, что-то не то сделал, он не правильно отображал вложенные категории :) Попробовал на тестовом проекте – все ок.
