### ISSUE TITLE
Пересмотреть модели новостей

### ISSUE THREAD

**Issue by olgaklimenko** [kolodnikovm/newsblog#3]
Две Почти одинаковые модели новостей.

**Comment by kolodnikovm** [comment]
Две модели нужны для реализации Draft-Publish новостей: в одной модели находится черновая новость, в другой – для публикаций.
Если есть какой-то другой подход, то готов выслушать :)

**Comment by olgaklimenko** [comment]
Тут на самом деле три замечания, и перед тем как их исправлять, лучше повторить принципы ООП:)

0) Названия классов `News` и `PublishedNews` не соответствуют содержимому. То есть ты будешь создавать инстанс который по сути является "Одной Новостью" с типом "Много Новостей"

1) Две модели с повторяющимися полями. Тут можно было воспользоваться одним из принципов ООП и не переписывать по два раза поля для каждой модели

2) У тебя тут есть дублирование информации:
Хранится черновая новость, и когда ее публикуем, создается точно такая же новость, но с доп. полем-сслыкой на черновую новость. Тут можно гораздо проще, обойтись всего одной моделью новостей.

**Comment by kolodnikovm** [comment]
Точно, но все же как обойтись без второй модели? Добавить черновые поля в модель публикуемых новостей?
С PublishedNews действительно, проще унаследовать было, не подумал :) А про названия я не совсем понял: что значит тип "Много новостей"? Один инстанс есть одна новость, так и есть.
