### ISSUE TITLE
Странная конструкция с юзером и автором

### ISSUE THREAD

**Issue by olgaklimenko** [kolodnikovm/newsblog#4]
Почему аватарка у юзера и все остальное у автора? И зачем вообще связь с юзером, если авторизации нет. Ощущение что планировалась авторизация и создание новостей через апи, но это не прослеживается в коде

**Comment by kolodnikovm** [comment]
В ТЗ были указаны юзер и автор как отдельные сущности, я подумал, что их следует разграничить. Все авторы – юзеры, но все все юзеры – авторы.

**Comment by olgaklimenko** [comment]
Тут мы кстати добавили в ТЗ еще регистрацию и авторизацию, надо тоже реализовать в этом приложении
